# Generated by Django 3.1.2 on 2020-10-12 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20201012_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
