# Generated by Django 3.0.3 on 2020-06-18 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartManager',
        ),
    ]
