# Generated by Django 3.1 on 2020-09-11 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_cart_sub_total'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
