# Generated by Django 3.1.2 on 2020-10-19 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_shipping_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
    ]
