# Generated by Django 3.0.3 on 2020-05-19 09:14

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=products.models.uploadImagePath),
        ),
    ]
