# Generated by Django 3.0.3 on 2020-05-19 16:54

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0004_auto_20200519_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.uploadImagePath),
        ),
    ]
