# Generated by Django 3.0.3 on 2020-05-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0006_product_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
