# Generated by Django 3.0.3 on 2020-05-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0008_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default='None'),
        ),
    ]
