# Generated by Django 3.0.3 on 2020-05-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0009_auto_20200526_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
